title: Make - Change - Improve
author: James Hicks
email: jhicks2306@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog about learning to code and finding a path forward, step by step.

# social links
github_username:  jhicks2306

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
